apiVersion: v1
kind: Service
metadata:
  name: httpd-service-datacenter
  namespace: httpd-namespace-datacenter
spec:
  type: NodePort
  selector:
    app: httpd-app-datacenter
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-datacenter
  namespace: httpd-namespace-datacenter
  labels:
    app: httpd-app-datacenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-app-datacenter
  template:
    metadata:
      labels:
        app: httpd-app-datacenter
    spec:
      containers:
        - name: httpd-container-datacenter
          image: httpd:latest
