- name: create archive and copy to hosts
  hosts: stapp01, stapp02, stapp03
  become: yes
  tasks:
    - name: create archive file, set owner, set group
      archive:
        path: /usr/src/security/
        dest: /opt/security/news.tar.gz
        format: gz
        force_archive: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"